---
- name: Include install_walg.yml
  ansible.builtin.include_tasks:
    file: install_walg.yml
    apply:
      tags: install
  when: not walg_in_docker
  tags:
    - install

- name: Include postgresql_config
  ansible.builtin.include_tasks: postgresql_conf.yml
  when:
    - postgresql_conf_change
    - not walg_in_docker

- name: Include dbs_backup
  ansible.builtin.include_tasks:
    file: "{{ walg_dbs }}_backup.yml"
    apply:
      tags: crontab
  when: walg_backup
  tags:
    - crontab

- name: Include dbs_restore
  ansible.builtin.include_tasks: "{{ walg_dbs }}_restore.yml"
  tags:
    - never
    - restore
