---
- name: Ensure log directory
  ansible.builtin.file:
    name: "{{ walg_log_path }}"
    owner: "{{ walg_cron_user }}"
    group: "{{ walg_cron_user }}"
    mode: 0764
    state: directory

- name: Create cron-job for backup
  ansible.builtin.cron:
    name: "wal-g backup"
    user: "{{ walg_cron_user }}"
    minute: "{{ walg_cron_time.minute | default('*') }}"
    hour: "{{ walg_cron_time.hour | int + 2 | default('*') }}"
    day: "{{ walg_cron_time.day | default('*') }}"
    month: "{{ walg_cron_time.month | default('*') }}"
    weekday: "{{ walg_cron_time.weekday | default('*') }}"
    job: "{{ walg_binary }} backup-push {{ walg_config.PGDATA }} >> {{ walg_log_path }}/walg_backup.log 2>&1"
    state: "{{ walg_cron_state }}"
  when: docker_containers is undefined

- name: Create cron-job for delete
  ansible.builtin.cron:
    name: "wal-g delete"
    user: "{{ walg_cron_user }}"
    minute: "{{ walg_cron_time.minute | default('*') }}"
    hour: "{{ walg_cron_time.hour | default('*') }}"
    day: "{{ walg_cron_time.day | default('*') }}"
    month: "{{ walg_cron_time.month | default('*') }}"
    weekday: "{{ walg_cron_time.weekday | default('*') }}"
    job: "{{ walg_binary }} delete before FIND_FULL $(date -d '-{{ walg_delete_before_days }} days' '+\\%FT\\%TZ') --confirm >> {{ walg_log_path }}/walg_delete.log 2>&1"
    state: "{{ walg_cron_state }}"
  when: docker_containers is undefined

- name: Create cron-job for backup for a few containers
  ansible.builtin.cron:
    name: "wal-g backup {{ item.walg_container_name }}"
    user: "{{ walg_cron_user }}"
    minute: "{{ item.walg_cron_time.minute | default('*') }}"
    hour: "{{ item.walg_cron_time.hour | int + 2 | default('*') }}"
    day: "{{ item.walg_cron_time.day | default('*') }}"
    month: "{{ item.walg_cron_time.month | default('*') }}"
    weekday: "{{ item.walg_cron_time.weekday | default('*') }}"
    job: "/usr/bin/docker exec -i {{ item.walg_container_name }} wal-g.sh backup-push {{ walg_config.PGDATA }} >> {{ walg_log_path }}/walg_backup.log 2>&1"
    state: "{{ walg_cron_state }}"
  when: docker_containers is defined
  with_items: "{{ docker_containers }}"

- name: Create cron-job for delete for a few containers
  ansible.builtin.cron:
    name: "wal-g delete {{ item.walg_container_name }}"
    user: "{{ walg_cron_user }}"
    minute: "{{ item.walg_cron_time.minute | default('*') }}"
    hour: "{{ item.walg_cron_time.hour | default('*') }}"
    day: "{{ item.walg_cron_time.day | default('*') }}"
    month: "{{ item.walg_cron_time.month | default('*') }}"
    weekday: "{{ item.walg_cron_time.weekday | default('*') }}"
    job: "/usr/bin/docker exec -i {{ item.walg_container_name }} wal-g.sh delete before FIND_FULL $(date -d '-{{ walg_delete_before_days }} days' '+\\%FT\\%TZ') --confirm >> {{ walg_log_path }}/walg_delete.log 2>&1"
    state: "{{ walg_cron_state }}"
  when: docker_containers is defined
  with_items: "{{ docker_containers }}"

