---
- name: Stop postgresql
  become: yes
  ansible.builtin.service:
    name: postgresql
    state: stopped
  tags:
    - restore

- name: Delete old base directory
  ansible.builtin.file:
    name: "{{ walg_config.PGDATA }}"
    state: absent
  tags:
    - restore

- name: Restopre base from backup
  become_user: "{{ walg_user }}"
  ansible.builtin.command: "{{ walg_binary }} backup-fetch {{ walg_config.PGDATA }} {{ walg_restore_name }}"
  register: my_output
  changed_when: my_output.rc != 0
  tags:
    - restore

- name: Touch recovery.signal
  ansible.builtin.file:
    name: "{{ walg_config.PGDATA }}/recovery.signal"
    state: touch
    owner: "postgres"
    group: "postgres"
    mode: '0644'
  tags:
    - restore

- name: Copy postgresql config for recovery
  ansible.builtin.template:
    src: wal-g-recovery.conf.j2
    dest: "{{ postgresql_conf_dir }}/conf.d/wal-g-recovery.conf"
    owner: "postgres"
    group: "postgres"
    mode: '0644'
  tags:
    - restore

- name: Start postgerql
  become: yes
  ansible.builtin.service:
    name: postgresql
    state: started
  tags:
    - restore

- name: Delete postgresql config for recovery
  ansible.builtin.file:
    name: "{{ postgresql_conf_dir }}/conf.d/wal-g-recovery.conf"
    state: absent
  tags:
    - restore
