---
- name: Stop postgresql
  become: yes
  service: name=postgresql state=stopped
  tags:
    - restore

- name: Delete old base directory
  file:
    name: "{{ walg_config.PGDATA }}"
    state: absent
  tags:
    - restore

- name: Restopre base from backup
  become_user: "{{ walg_user }}"
  command: "{{ walg_binary_path }}/wal-g backup-fetch {{ walg_config.PGDATA }} {{ walg_restore_name }}"
  tags:
    - restore

- name: Touch recovery.signal
  file:
    name: "{{ walg_config.PGDATA }}/recovery.signal"
    state: touch
    owner: "postgres"
    group: "postgres"
    mode: '0644'
  tags:
    - restore

- name: Copy postgresql config for recovery
  template:
    src: wal-g-recovery.conf.j2
    dest: "{{ postgresql_conf_dir }}/conf.d/wal-g-recovery.conf"
    owner: "postgres"
    group: "postgres"
    mode: '0644'
  tags:
    - restore

- name: Start postgerql
  become: yes
  service: name=postgresql state=started
  tags:
    - restore

- name: Delete postgresql config for recovery
  file:
    name: "{{ postgresql_conf_dir }}/conf.d/wal-g-recovery.conf"
    state: absent
  tags:
    - restore
